server:
 port: 8888

spring:
 application:
   name: config-service
#  profiles:
#    active: native
 cloud:
   config:
     server:
      #  native:
      #    search-locations: file:///E:\KOSA\MSA\native-file-repo
       git:
         uri: https://github.com/KOSA-Final-oio-project/config